In [1]:
import numpy as np

In [2]:
num = np.array([56,33,12,78,52,68,25])

In [3]:
num

array([56, 33, 12, 78, 52, 68, 25])

In [4]:
type(num)

numpy.ndarray

In [5]:
print(num) #list show list but not having comma in between

[56 33 12 78 52 68 25]


In [6]:
num.dtype

dtype('int32')

In [22]:
num = np.array([56,33,12,78,52,68,25], dtype= np.int16)

In [23]:
num

array([56, 33, 12, 78, 52, 68, 25], dtype=int16)

In [24]:
num[5]

68

In [25]:
num[5]=22  # mutable

In [26]:
num

array([56, 33, 12, 78, 52, 22, 25], dtype=int16)

In [27]:
num.ndim

1

In [28]:
num.min()

12

In [29]:
num.max()

78

In [30]:
num.size

7

In [31]:
num1 =np.array([45.67,23.56,78.25,89.82])

In [32]:
num1.dtype

dtype('float64')

In [33]:
num1.tolist()

[45.67, 23.56, 78.25, 89.82]

In [34]:
num1

array([45.67, 23.56, 78.25, 89.82])

In [35]:
num *2

array([112,  66,  24, 156, 104,  44,  50], dtype=int16)

In [36]:
num>40  #check the condition

array([ True, False, False,  True,  True, False, False])

In [37]:
num[num>40]   # filter true value  i.e. grater than 40

array([56, 78, 52], dtype=int16)

#### Matrix 
###### 2-d array

In [40]:
M = np.array([[5,6,7],[2,4,3],[6,8,9],[0,1,3]])

In [41]:
M


array([[5, 6, 7],
       [2, 4, 3],
       [6, 8, 9],
       [0, 1, 3]])

In [42]:
M.ndim

2

In [43]:
M.shape ##shows in rows and col

(4, 3)

In [44]:
M.size

12

In [45]:
M.dtype

dtype('int32')

In [46]:
M[0][1] #0th row and 1st col

6

In [47]:
M[0,1] 

6

In [52]:
M[0,1] =6

In [53]:
M

array([[5, 6, 7],
       [2, 4, 3],
       [6, 8, 9],
       [0, 1, 3]])

In [54]:
M.T # transpose i.e. converting rows to col

array([[5, 2, 6, 0],
       [6, 4, 8, 1],
       [7, 3, 9, 3]])

In [55]:
M.transpose()

array([[5, 2, 6, 0],
       [6, 4, 8, 1],
       [7, 3, 9, 3]])

In [56]:
M.reshape(6,2)

array([[5, 6],
       [7, 2],
       [4, 3],
       [6, 8],
       [9, 0],
       [1, 3]])

In [58]:
M.flatten()

array([5, 6, 7, 2, 4, 3, 6, 8, 9, 0, 1, 3])

In [61]:
M.reshape([12]) # if know exact no. of data in M

array([5, 6, 7, 2, 4, 3, 6, 8, 9, 0, 1, 3])

In [62]:
M.reshape([-1])   # if don't know exact no. of data in M

array([5, 6, 7, 2, 4, 3, 6, 8, 9, 0, 1, 3])

In [63]:
M.reshape([-1,4]) # only want 4 col and don't know no. of data 

array([[5, 6, 7, 2],
       [4, 3, 6, 8],
       [9, 0, 1, 3]])